# Generated by Django 4.0.1 on 2022-01-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('provider', models.CharField(max_length=100)),
                ('provider_id', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_per_meter', models.FloatField(blank=True, null=True)),
                ('living_area', models.FloatField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('floor_in_total', models.IntegerField(blank=True, null=True)),
                ('last_floor', models.BooleanField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
