# Generated by Django 4.0.1 on 2022-01-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatoffer',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
