# Generated by Django 4.0.1 on 2022-01-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_flatoffer_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatoffer',
            old_name='rooms',
            new_name='number_of_rooms',
        ),
    ]
