# Generated by Django 4.0.1 on 2022-01-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_rename_rooms_flatoffer_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatoffer',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
