# Generated by Django 4.0.1 on 2022-01-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_flatoffer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatoffer',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
