version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app/code
    command: python manage.py runserver 0.0.0.0:8000
